FROM linuxserver/nginx

COPY ./nginx/config/jira.conf /etc/nginx/conf.d/jira.conf
COPY ./nginx/config/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/certs/heuristic.key /etc/ssl/STAR_heuristic-cons.org.key
COPY ./nginx/certs/heuristic.crt /etc/ssl/STAR_heuristic-cons.org.crt
