CREATE USER jira WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1;
CREATE DATABASE jiraprod
    WITH 
    OWNER = postgres
    TEMPLATE = template0
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    CONNECTION LIMIT = -1;
GRANT ALL PRIVILEGES ON DATABASE jiraprod TO jira;

CREATE USER confluence WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1;
CREATE DATABASE confluenceprod
    WITH 
    OWNER = postgres
    TEMPLATE = template0
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    CONNECTION LIMIT = -1;
GRANT ALL PRIVILEGES ON DATABASE confluenceprod TO confluence;

CREATE USER bitbucket WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1;
CREATE DATABASE bitbucketprod
    WITH 
    OWNER = postgres
    TEMPLATE = template0
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    CONNECTION LIMIT = -1;
GRANT ALL PRIVILEGES ON DATABASE bitbucketprod TO bitbucket;
ALTER USER jira       WITH PASSWORD 'QT8FwCrI9YWDQEP';
ALTER USER confluence WITH PASSWORD 'z9OyMTFSbaBxmsn';
ALTER USER bitbucket  WITH PASSWORD 'fdsWjln3u5Bhtr4';